---
name: "runspec"
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.13
  - nodejs
  - pre-commit
  - prettier
  - markdownlint-cli
  - yamllint
  - taplo
  - go-shfmt
  - shellcheck
  - libxml2
  - jq
  - coreutils
  - pip
  - pip:
      - editorconfig-checker
