import {
  agentPolicy,
  defineRunSpecFramework,
  diagramTarget,
  infrastructureAdapter,
  productCapability,
  productFlow,
  qualityGate,
  serviceTarget,
  sourceOfTruthPolicy,
  threatModel,
  verificationHarness,
  workspaceCapability,
} from "../core/builders.js";

export const runSpecFramework = defineRunSpecFramework({
  name: "RunSpec",
  purpose: "Build production applications from executable product definitions without markdown-first specification tools.",
  sourceOfTruth: sourceOfTruthPolicy({
    executableDefinitionsOnly: true,
    handWrittenMarkdownFiles: ["README.md"],
    generatedArtifactDirectory: ".runspec/generated",
    generatedArtifactsAreReadOnlyForAgents: true,
    commentsAsSpecificationAllowed: false,
    externalSpecFrameworksAllowed: false,
  }),
  workspaceCapabilities: [
    workspaceCapability({
      mode: "single-service",
      supportsMultipleServices: false,
      supportsSharedLibraries: true,
      supportsIndependentServiceVerification: true,
      supportsCrossServiceVerification: false,
      supportsGeneratedCiTopology: true,
    }),
    workspaceCapability({
      mode: "monorepo",
      supportsMultipleServices: true,
      supportsSharedLibraries: true,
      supportsIndependentServiceVerification: true,
      supportsCrossServiceVerification: true,
      supportsGeneratedCiTopology: true,
    }),
    workspaceCapability({
      mode: "multi-repo",
      supportsMultipleServices: true,
      supportsSharedLibraries: false,
      supportsIndependentServiceVerification: true,
      supportsCrossServiceVerification: true,
      supportsGeneratedCiTopology: true,
    }),
    workspaceCapability({
      mode: "hybrid",
      supportsMultipleServices: true,
      supportsSharedLibraries: true,
      supportsIndependentServiceVerification: true,
      supportsCrossServiceVerification: true,
      supportsGeneratedCiTopology: true,
    }),
  ],
  serviceTargets: [
    serviceTarget({
      id: "go-http-service",
      language: "go",
      framework: "go-http",
      layers: ["domain", "application", "ports", "adapters", "configuration", "observability"],
      generatedCodeAreas: ["domain", "usecases", "repositories", "http", "messaging", "config", "tests"],
      requiredHarnesses: ["unit", "domain", "api", "contract", "architecture", "security", "observability", "integration"],
      requiredGates: ["requirement", "implementation", "architecture", "api", "security", "observability", "integration", "report"],
    }),
    serviceTarget({
      id: "spring-boot-service",
      language: "java",
      framework: "spring-boot",
      layers: ["domain", "application", "ports", "adapters", "configuration", "observability"],
      generatedCodeAreas: ["domain", "application-services", "repositories", "controllers", "messaging", "configuration", "tests"],
      requiredHarnesses: ["unit", "domain", "api", "contract", "database", "architecture", "security", "observability", "integration"],
      requiredGates: ["requirement", "implementation", "architecture", "api", "database", "security", "observability", "integration", "report"],
    }),
    serviceTarget({
      id: "typescript-node-service",
      language: "typescript",
      framework: "node-http",
      layers: ["domain", "application", "ports", "adapters", "configuration", "observability"],
      generatedCodeAreas: ["domain", "usecases", "repositories", "http", "messaging", "config", "tests"],
      requiredHarnesses: ["unit", "domain", "api", "contract", "architecture", "security", "observability", "integration"],
      requiredGates: ["requirement", "implementation", "architecture", "api", "security", "observability", "integration", "report"],
    }),
    serviceTarget({
      id: "event-worker",
      language: "go",
      framework: "worker",
      layers: ["domain", "application", "ports", "adapters", "configuration", "observability"],
      generatedCodeAreas: ["domain", "handlers", "event-consumers", "event-producers", "idempotency", "config", "tests"],
      requiredHarnesses: ["unit", "event-consumer", "event-producer", "contract", "architecture", "security", "observability", "integration"],
      requiredGates: ["requirement", "implementation", "architecture", "messaging", "security", "observability", "integration", "report"],
    }),
  ],
  infrastructureAdapters: [
    infrastructureAdapter({ kind: "postgres", generatedAssets: ["migration", "repository-port", "repository-adapter", "testcontainer", "fixtures"], harnesses: ["database", "integration"], gates: ["database", "security", "observability"] }),
    infrastructureAdapter({ kind: "kafka", generatedAssets: ["event-schema", "producer", "consumer", "testcontainer", "dead-letter-handler", "idempotency-store"], harnesses: ["event-producer", "event-consumer", "contract", "integration"], gates: ["messaging", "security", "observability"] }),
    infrastructureAdapter({ kind: "rabbitmq", generatedAssets: ["exchange", "queue", "binding", "producer", "consumer", "dead-letter-queue", "testcontainer"], harnesses: ["event-producer", "event-consumer", "contract", "integration"], gates: ["messaging", "security", "observability"] }),
    infrastructureAdapter({ kind: "redis", generatedAssets: ["cache-port", "cache-adapter", "testcontainer", "ttl-policy"], harnesses: ["integration"], gates: ["implementation", "security", "observability"] }),
    infrastructureAdapter({ kind: "vault", generatedAssets: ["secret-provider-port", "secret-provider-adapter", "local-dev-secret-harness"], harnesses: ["security", "integration"], gates: ["security", "implementation"] }),
    infrastructureAdapter({ kind: "object-storage", generatedAssets: ["storage-port", "storage-adapter", "bucket-policy", "testcontainer"], harnesses: ["integration", "security"], gates: ["implementation", "security", "observability"] }),
  ],
  productCapabilities: [
    productCapability({
      id: "APPLICATION_BUILDER",
      title: "RunSpec builds complete production service slices from executable capability definitions",
      actor: "product-owner-with-agent",
      businessOutcome: "A product owner can express intent once and receive verifiable production code skeletons across service, data, messaging, security, and observability layers.",
      ownerService: "runspec-cli",
      implementation: {
        domainObjects: ["ProductCapability", "ServiceTarget", "ImplementationContract"],
        useCases: ["GenerateServiceSlice", "ValidateCapabilityCompleteness"],
        ports: ["TemplateRepository", "FileWriter", "VerificationRunner"],
        adapters: ["GoServiceTemplate", "SpringBootServiceTemplate", "NodeServiceTemplate"],
        repositories: ["CapabilityManifestRepository"],
        generatedSkeletonRequired: true,
      },
      scenarios: [
        {
          id: "APPLICATION_BUILDER-001",
          title: "generates vertical slice with domain, use case, adapters, harnesses, and gates",
          given: ["an executable product capability", "a selected service target", "a selected workspace mode"],
          when: "the service builder runs",
          then: ["domain skeleton exists", "application use case skeleton exists", "ports exist", "adapters exist", "verification harnesses exist", "quality gates are registered"],
          verifiesThreats: ["APPLICATION_BUILDER-TAMPERING-001"],
          harnesses: ["unit", "architecture", "integration"],
        },
        {
          id: "APPLICATION_BUILDER-002",
          title: "rejects completion when implementation gate fails",
          given: ["a generated service slice", "a missing repository adapter"],
          when: "the agent asks to complete the task",
          then: ["completion is rejected", "next task points to failing implementation area"],
          verifiesThreats: ["APPLICATION_BUILDER-REPUDIATION-001"],
          harnesses: ["architecture", "integration"],
        },
      ],
      contracts: {
        http: [],
        events: [{ name: "runspec.service_slice.generated", producer: "runspec-cli", consumers: ["runspec-verify"], schema: "ServiceSliceGenerated", delivery: "at-least-once", idempotencyKey: "capabilityId", deadLetterPolicy: "fail-generation-and-preserve-evidence" }],
        data: [{ name: "CapabilityManifest", store: "postgres", classification: "internal", migrationRequired: true, fields: [{ name: "id", type: "string", required: true, pii: false }, { name: "status", type: "string", required: true, pii: false }, { name: "createdAt", type: "timestamp", required: true, pii: false }] }],
      },
      security: {
        authentication: "local-cli-or-ci-identity",
        authorization: ["workspace-write-access"],
        validation: ["capability-schema-validation", "path-boundary-validation"],
        sensitiveDataRules: ["do-not-generate-secrets", "mask-local-env-values"],
      },
      observability: {
        traces: ["runspec.builder.generate_slice"],
        metrics: ["runspec_builder_generated_slices_total"],
        logs: ["capabilityId", "serviceTarget", "workspaceMode", "result"],
        correlationIdRequired: true,
      },
      gates: ["requirement", "implementation", "architecture", "database", "security", "threat-model", "observability", "integration", "report"],
    }),
    productCapability({
      id: "ENTERPRISE_HARNESS",
      title: "RunSpec verifies complex applications through generated executable harnesses",
      actor: "developer-or-agent",
      businessOutcome: "A complex enterprise application is accepted only when all generated harnesses and blocking gates pass.",
      ownerService: "runspec-verify",
      implementation: {
        domainObjects: ["VerificationHarness", "QualityGate", "VerificationResult"],
        useCases: ["RunAllBlockingGates", "CreateVerificationEvidence"],
        ports: ["ProcessRunner", "ReportWriter", "ArtifactStore"],
        adapters: ["NodeProcessRunner", "JsonReportWriter", "GeneratedArtifactStore"],
        repositories: ["VerificationResultRepository"],
        generatedSkeletonRequired: true,
      },
      scenarios: [{ id: "ENTERPRISE_HARNESS-001", title: "runs architecture, security, messaging, database, observability, and integration gates", given: ["a generated application workspace", "registered quality gates"], when: "runspec verify executes", then: ["all blocking gates execute", "failed gate blocks completion", "evidence is written under generated artifacts"], verifiesThreats: ["ENTERPRISE_HARNESS-REPUDIATION-001"], harnesses: ["architecture", "security", "database", "observability", "integration"] }],
      contracts: { http: [], events: [], data: [] },
      security: { authentication: "ci-or-local-user", authorization: ["workspace-read-access"], validation: ["command-allowlist"], sensitiveDataRules: ["generated-evidence-must-mask-secrets"] },
      observability: { traces: ["runspec.verify.run"], metrics: ["runspec_verify_gate_failures_total"], logs: ["gate", "capabilityId", "result"], correlationIdRequired: true },
      gates: ["requirement", "implementation", "architecture", "messaging", "database", "security", "threat-model", "observability", "integration", "report"],
    }),
  ],
  flows: [
    productFlow({
      id: "APPLICATION_BUILDER-FLOW",
      title: "Agent builds a production slice from executable capability code",
      capabilityId: "APPLICATION_BUILDER",
      participants: ["product-owner", "agent", "runspec-cli", "generated-service", "runspec-verify"],
      steps: [
        { from: "product-owner", to: "agent", action: "describes intent" },
        { from: "agent", to: "runspec-cli", action: "writes executable capability" },
        { from: "runspec-cli", to: "generated-service", action: "generates service skeleton" },
        { from: "agent", to: "generated-service", action: "implements production code" },
        { from: "runspec-verify", to: "generated-service", action: "runs blocking gates" },
      ],
    }),
  ],
  threatModels: [
    threatModel({
      id: "APPLICATION_BUILDER-THREATS",
      capabilityId: "APPLICATION_BUILDER",
      assets: ["product definition", "generated code", "verification evidence"],
      entrypoints: ["runspec generate", "runspec verify", "runspec agent next"],
      threats: [
        { id: "APPLICATION_BUILDER-TAMPERING-001", category: "tampering", scenario: "agent edits generated evidence instead of source code", mitigations: ["generated artifact denylist", "repository hygiene gate"], verifiedByScenarioIds: ["APPLICATION_BUILDER-001"] },
        { id: "APPLICATION_BUILDER-REPUDIATION-001", category: "repudiation", scenario: "agent claims completion without passing executable gates", mitigations: ["required command policy", "blocking gate result"], verifiedByScenarioIds: ["APPLICATION_BUILDER-002"] },
      ],
    }),
    threatModel({
      id: "ENTERPRISE_HARNESS-THREATS",
      capabilityId: "ENTERPRISE_HARNESS",
      assets: ["quality gates", "execution report", "generated evidence"],
      entrypoints: ["runspec verify"],
      threats: [{ id: "ENTERPRISE_HARNESS-REPUDIATION-001", category: "repudiation", scenario: "failing gate is ignored", mitigations: ["all gates are blocking", "verification report is generated"], verifiedByScenarioIds: ["ENTERPRISE_HARNESS-001"] }],
    }),
  ],
  qualityGates: [
    qualityGate({ kind: "requirement", name: "every capability has executable scenarios", blocking: true, command: "runspec verify requirements", evidence: ".runspec/generated/requirements.json" }),
    qualityGate({ kind: "implementation", name: "implementation contracts are satisfied", blocking: true, command: "runspec verify implementation", evidence: ".runspec/generated/implementation.json" }),
    qualityGate({ kind: "architecture", name: "architecture boundaries are enforced", blocking: true, command: "runspec verify architecture", evidence: ".runspec/generated/architecture.json" }),
    qualityGate({ kind: "api", name: "api contracts are verified", blocking: true, command: "runspec verify api", evidence: ".runspec/generated/api.json" }),
    qualityGate({ kind: "messaging", name: "event producers and consumers are verified", blocking: true, command: "runspec verify messaging", evidence: ".runspec/generated/messaging.json" }),
    qualityGate({ kind: "database", name: "database contracts and migrations are verified", blocking: true, command: "runspec verify database", evidence: ".runspec/generated/database.json" }),
    qualityGate({ kind: "security", name: "security policy is executable and verified", blocking: true, command: "runspec verify security", evidence: ".runspec/generated/security.json" }),
    qualityGate({ kind: "threat-model", name: "threat model mitigations are verified", blocking: true, command: "runspec verify threats", evidence: ".runspec/generated/threats.json" }),
    qualityGate({ kind: "observability", name: "logs, metrics, traces, and correlation ids are verified", blocking: true, command: "runspec verify observability", evidence: ".runspec/generated/observability.json" }),
    qualityGate({ kind: "integration", name: "cross-service flows are verified", blocking: true, command: "runspec verify integration", evidence: ".runspec/generated/integration.json" }),
    qualityGate({ kind: "report", name: "reports and diagrams are generated from execution", blocking: true, command: "runspec report", evidence: ".runspec/generated/report.json" }),
    qualityGate({ kind: "repository-hygiene", name: "only README.md is hand-written markdown", blocking: true, command: "runspec verify repository", evidence: ".runspec/generated/repository.json" }),
  ],
  harnesses: [
    verificationHarness({ kind: "unit", name: "unit behavior harness", generatedFor: ["domain", "application"], requiredForProduction: true }),
    verificationHarness({ kind: "architecture", name: "architecture dependency harness", generatedFor: ["workspace", "service"], requiredForProduction: true }),
    verificationHarness({ kind: "security", name: "security policy harness", generatedFor: ["capability", "service"], requiredForProduction: true }),
    verificationHarness({ kind: "database", name: "database contract harness", generatedFor: ["postgres"], requiredForProduction: true }),
    verificationHarness({ kind: "event-producer", name: "event producer contract harness", generatedFor: ["kafka", "rabbitmq"], requiredForProduction: true }),
    verificationHarness({ kind: "event-consumer", name: "event consumer contract harness", generatedFor: ["kafka", "rabbitmq"], requiredForProduction: true }),
    verificationHarness({ kind: "observability", name: "observability harness", generatedFor: ["service", "flow"], requiredForProduction: true }),
    verificationHarness({ kind: "integration", name: "integration flow harness", generatedFor: ["workspace", "flow"], requiredForProduction: true }),
  ],
  diagramTargets: [
    diagramTarget({ kind: "flowchart", source: "flow", outputFormat: "mermaid", generatedOnly: true }),
    diagramTarget({ kind: "sequence", source: "flow", outputFormat: "mermaid", generatedOnly: true }),
    diagramTarget({ kind: "component", source: "workspace", outputFormat: "plantuml", generatedOnly: true }),
    diagramTarget({ kind: "deployment", source: "workspace", outputFormat: "plantuml", generatedOnly: true }),
    diagramTarget({ kind: "threat-model", source: "threat-model", outputFormat: "json", generatedOnly: true }),
  ],
  agentPolicy: agentPolicy({
    agentReads: ["README.md", "src/**/*.ts"],
    allowedToModify: ["src/**", "test/**", "package.json", "tsconfig.json", ".github/workflows/**"],
    deniedToModify: [".runspec/generated/**", "dist/**", "node_modules/**", "*.md", "!README.md"],
    requiredCommandsBeforeCompletion: ["npm test"],
    completionRequiresAllBlockingGates: true,
    nextTaskStrategy: "first-failing-gate",
  }),
});
