import type {
  GeneratedFile,
  ProductCapability,
  ServiceTarget,
  SkeletonGenerator,
} from "../model.js";
import { skeletonGenerator } from "../builders.js";
import { pascalCase, sanitiseForComment } from "./_shared.js";

export const goHttpGenerator: SkeletonGenerator = skeletonGenerator({
  id: "go-http",
  description: "Go HTTP service skeleton generator",
  language: "go",
  framework: "go-http",
  generate(capability, service) {
    const moduleName = `example.com/${service.id}`;
    const header = generatedHeader(capability, service);
    const files: GeneratedFile[] = [];

    files.push({ path: "go.mod", content: goMod(moduleName) });
    files.push({ path: "main.go", content: mainGo(header, moduleName) });

    capability.implementation.domainObjects.forEach(name => {
      files.push({ path: `domain/${snakeCase(name)}.go`, content: domainFile(header, name) });
    });
    capability.implementation.useCases.forEach(name => {
      files.push({ path: `usecases/${snakeCase(name)}.go`, content: useCaseFile(header, name) });
    });
    capability.implementation.ports.forEach(name => {
      files.push({ path: `ports/${snakeCase(name)}.go`, content: portFile(header, name) });
    });
    capability.implementation.adapters.forEach(name => {
      files.push({ path: `adapters/${snakeCase(name)}.go`, content: adapterFile(header, name) });
    });
    capability.implementation.repositories.forEach(name => {
      files.push({ path: `repositories/${snakeCase(name)}.go`, content: repositoryFile(header, name) });
    });

    files.push({ path: "http/handler.go", content: handlerFile(header) });

    capability.scenarios.forEach(scenario => {
      files.push({
        path: `tests/${snakeCase(scenario.id)}_test.go`,
        content: scenarioTestFile(header, scenario.id, scenario.title),
      });
    });

    return files;
  },
});

function generatedHeader(capability: ProductCapability, service: ServiceTarget): string {
  return [
    "// Code generated by runspec. DO NOT EDIT.",
    `// Source: capability "${sanitiseForComment(capability.id)}", service "${sanitiseForComment(service.id)}".`,
    "",
  ].join("\n");
}


function goMod(moduleName: string): string {
  return [`module ${moduleName}`, "", "go 1.26", ""].join("\n");
}

function mainGo(header: string, moduleName: string): string {
  return [
    header,
    "package main",
    "",
    `import _ "${moduleName}/http"`,
    "",
    "func main() {",
    "}",
    "",
  ].join("\n");
}

function domainFile(header: string, name: string): string {
  return [
    header,
    "package domain",
    "",
    `// ${name} is a generated domain type. Extend by adding fields.`,
    `type ${name} struct{}`,
    "",
  ].join("\n");
}

function useCaseFile(header: string, name: string): string {
  return [
    header,
    "package usecases",
    "",
    `// ${name} is a generated use case interface.`,
    `type ${name} interface {`,
    "\tExecute() error",
    "}",
    "",
  ].join("\n");
}

function portFile(header: string, name: string): string {
  return [
    header,
    "package ports",
    "",
    `// ${name} is a generated port interface.`,
    `type ${name} interface{}`,
    "",
  ].join("\n");
}

function adapterFile(header: string, name: string): string {
  return [
    header,
    "package adapters",
    "",
    `// ${name} is a generated adapter struct.`,
    `type ${name} struct{}`,
    "",
  ].join("\n");
}

function repositoryFile(header: string, name: string): string {
  return [
    header,
    "package repositories",
    "",
    `// ${name} is a generated repository interface.`,
    `type ${name} interface{}`,
    "",
  ].join("\n");
}

function handlerFile(header: string): string {
  return [
    header,
    "package http",
    "",
    `import "net/http"`,
    "",
    "// Handler is the generated HTTP handler base. Wire routes here.",
    "type Handler struct{}",
    "",
    "// ServeHTTP routes requests to the appropriate use case.",
    "func (h *Handler) ServeHTTP(w http.ResponseWriter, r *http.Request) {",
    "\t_ = w",
    "\t_ = r",
    "}",
    "",
  ].join("\n");
}

function scenarioTestFile(header: string, scenarioId: string, scenarioTitle: string): string {
  const testName = `Test${pascalCase(scenarioId)}`;
  const escapedTitle = scenarioTitle.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
  return [
    header,
    "package tests",
    "",
    `import "testing"`,
    "",
    `// ${testName} is the generated test stub for scenario "${escapedTitle}".`,
    `func ${testName}(t *testing.T) {`,
    `\tt.Skip("runspec scenario not yet implemented")`,
    "}",
    "",
  ].join("\n");
}

function snakeCase(input: string): string {
  const sanitised = input
    .replace(/[-_]+/g, "_")
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1_$2")
    .toLowerCase()
    .replace(/[^a-z0-9_]/g, "_")
    .replace(/_+/g, "_")
    .replace(/^_|_$/g, "");
  return sanitised.length > 0 ? sanitised : "unnamed";
}
