import type {
  EventContract,
  GeneratedFile,
  ProductCapability,
  ServiceTarget,
  SkeletonGenerator,
} from "../model.js";
import { skeletonGenerator } from "../builders.js";
import { pascalCase, sanitiseForComment } from "./_shared.js";

export const goWorkerGenerator: SkeletonGenerator = skeletonGenerator({
  id: "go-worker",
  description: "Go event-worker skeleton generator (Kafka/RabbitMQ-agnostic stubs)",
  language: "go",
  framework: "worker",
  generate(capability, service) {
    const moduleName = `example.com/${service.id}`;
    const header = generatedHeader(capability, service);
    const files: GeneratedFile[] = [];

    files.push({ path: "go.mod", content: goMod(moduleName) });
    files.push({ path: "main.go", content: mainGo(header, moduleName) });

    capability.implementation.domainObjects.forEach(name => {
      files.push({ path: `domain/${snakeCase(name)}.go`, content: domainFile(header, name) });
    });

    const consumedEvents = capability.contracts.events;
    const producedEvents = capability.contracts.events;

    consumedEvents.forEach(event => {
      const eventName = snakeCase(event.name);
      const className = pascalCase(event.name);
      files.push({
        path: `event-consumers/${eventName}_consumer.go`,
        content: consumerFile(header, className, event),
      });
      files.push({
        path: `idempotency/${eventName}_keys.go`,
        content: idempotencyFile(header, className, event),
      });
    });

    producedEvents.forEach(event => {
      const eventName = snakeCase(event.name);
      const className = pascalCase(event.name);
      files.push({
        path: `event-producers/${eventName}_producer.go`,
        content: producerFile(header, className, event),
      });
    });

    capability.scenarios.forEach(scenario => {
      files.push({
        path: `handlers/${snakeCase(scenario.id)}.go`,
        content: handlerFile(header, pascalCase(scenario.id)),
      });
    });

    files.push({ path: "config/broker.go", content: brokerConfigFile(header) });

    capability.scenarios.forEach(scenario => {
      files.push({
        path: `tests/${snakeCase(scenario.id)}_test.go`,
        content: scenarioTestFile(header, scenario.id, scenario.title),
      });
    });

    return files;
  },
});

function generatedHeader(capability: ProductCapability, service: ServiceTarget): string {
  return [
    "// Code generated by runspec. DO NOT EDIT.",
    `// Source: capability "${sanitiseForComment(capability.id)}", service "${sanitiseForComment(service.id)}".`,
    "",
  ].join("\n");
}

function goMod(moduleName: string): string {
  return [`module ${moduleName}`, "", "go 1.26", ""].join("\n");
}

function mainGo(header: string, moduleName: string): string {
  return [
    header,
    "package main",
    "",
    `import (`,
    `\t"context"`,
    `\t"os/signal"`,
    `\t"syscall"`,
    `\t_ "${moduleName}/event-consumers"`,
    `\t_ "${moduleName}/event-producers"`,
    `)`,
    "",
    "func main() {",
    "\tctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)",
    "\tdefer stop()",
    "\t<-ctx.Done()",
    "}",
    "",
  ].join("\n");
}

function domainFile(header: string, name: string): string {
  return [
    header,
    "package domain",
    "",
    `// ${name} is a generated domain type. Extend by adding fields.`,
    `type ${name} struct{}`,
    "",
  ].join("\n");
}

function consumerFile(header: string, className: string, event: EventContract): string {
  return [
    header,
    "package eventconsumers",
    "",
    `// ${className}Consumer consumes "${sanitiseForComment(event.name)}" events.`,
    `// Delivery guarantee: ${event.delivery}. Idempotency key: ${sanitiseForComment(event.idempotencyKey)}.`,
    `type ${className}Consumer interface {`,
    "\tConsume(payload []byte) error",
    "}",
    "",
  ].join("\n");
}

function producerFile(header: string, className: string, event: EventContract): string {
  return [
    header,
    "package eventproducers",
    "",
    `// ${className}Producer produces "${sanitiseForComment(event.name)}" events.`,
    `// Delivery guarantee: ${event.delivery}. Dead-letter policy: ${sanitiseForComment(event.deadLetterPolicy)}.`,
    `type ${className}Producer interface {`,
    "\tProduce(payload []byte) error",
    "}",
    "",
  ].join("\n");
}

function idempotencyFile(header: string, className: string, event: EventContract): string {
  return [
    header,
    "package idempotency",
    "",
    `// ${className}KeyExtractor returns the idempotency key for a "${sanitiseForComment(event.name)}" event.`,
    `// Key field declared by the runspec blueprint: ${sanitiseForComment(event.idempotencyKey)}.`,
    `type ${className}KeyExtractor interface {`,
    "\tKey(payload []byte) (string, error)",
    "}",
    "",
  ].join("\n");
}

function handlerFile(header: string, name: string): string {
  return [
    header,
    "package handlers",
    "",
    `// ${name} handles the generated scenario.`,
    `type ${name} struct{}`,
    "",
    `// Handle processes a single message for the scenario.`,
    `func (h *${name}) Handle(payload []byte) error {`,
    "\t_ = payload",
    "\treturn nil",
    "}",
    "",
  ].join("\n");
}

function brokerConfigFile(header: string): string {
  return [
    header,
    "package config",
    "",
    "// BrokerConfig declares the connection parameters injected at runtime.",
    "// Library choice (Kafka, RabbitMQ, ...) is intentionally not pinned in",
    "// the generated skeleton; wire your chosen client in the adapter layer.",
    "type BrokerConfig struct {",
    "\tBrokers     []string",
    "\tGroupID     string",
    "\tTopic       string",
    "\tDeadLetter  string",
    "}",
    "",
  ].join("\n");
}

function scenarioTestFile(header: string, scenarioId: string, scenarioTitle: string): string {
  const testName = `Test${pascalCase(scenarioId)}`;
  const escapedTitle = scenarioTitle
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/\t/g, "\\t");
  return [
    header,
    "package tests",
    "",
    `import "testing"`,
    "",
    `// ${testName} is the generated test stub for scenario "${escapedTitle}".`,
    `func ${testName}(t *testing.T) {`,
    `\tt.Skip("runspec scenario not yet implemented")`,
    "}",
    "",
  ].join("\n");
}

function snakeCase(input: string): string {
  const sanitised = input
    .replace(/[-_.]+/g, "_")
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1_$2")
    .toLowerCase()
    .replace(/[^a-z0-9_]/g, "_")
    .replace(/_+/g, "_")
    .replace(/^_|_$/g, "");
  return sanitised.length > 0 ? sanitised : "unnamed";
}
