import type {
  GeneratedFile,
  ProductCapability,
  ServiceTarget,
  SkeletonGenerator,
} from "../model.js";
import { skeletonGenerator } from "../builders.js";
import { pascalCase, sanitiseForComment } from "./_shared.js";

export const nodeHttpGenerator: SkeletonGenerator = skeletonGenerator({
  id: "node-http",
  description: "TypeScript Node.js HTTP service skeleton generator",
  language: "typescript",
  framework: "node-http",
  generate(capability, service) {
    const header = generatedHeader(capability, service);
    const packageName = npmPackageName(service.id);
    const files: GeneratedFile[] = [];

    files.push({ path: "package.json", content: packageJson(header, packageName) });
    files.push({ path: "tsconfig.json", content: tsconfigJson(header) });
    files.push({ path: "src/main.ts", content: mainFile(header) });

    capability.implementation.domainObjects.forEach(name => {
      const className = pascalCase(name);
      files.push({
        path: `src/domain/${className}.ts`,
        content: domainFile(header, className),
      });
    });
    capability.implementation.useCases.forEach(name => {
      const className = pascalCase(name);
      files.push({
        path: `src/usecases/${className}.ts`,
        content: useCaseFile(header, className),
      });
    });
    capability.implementation.ports.forEach(name => {
      const className = pascalCase(name);
      files.push({
        path: `src/ports/${className}.ts`,
        content: portFile(header, className),
      });
    });
    capability.implementation.adapters.forEach(name => {
      const className = pascalCase(name);
      files.push({
        path: `src/adapters/${className}.ts`,
        content: adapterFile(header, className),
      });
    });
    capability.implementation.repositories.forEach(name => {
      const className = pascalCase(name);
      files.push({
        path: `src/repositories/${className}.ts`,
        content: repositoryFile(header, className),
      });
    });

    files.push({ path: "src/http/handler.ts", content: handlerFile(header) });

    capability.scenarios.forEach(scenario => {
      const fileName = pascalCase(scenario.id);
      files.push({
        path: `test/${fileName}.test.ts`,
        content: scenarioTestFile(header, scenario.title),
      });
    });

    return files;
  },
});

function generatedHeader(capability: ProductCapability, service: ServiceTarget): string {
  return [
    "// Code generated by runspec. DO NOT EDIT.",
    `// Source: capability "${sanitiseForComment(capability.id)}", service "${sanitiseForComment(service.id)}".`,
    "",
  ].join("\n");
}

function packageJson(header: string, packageName: string): string {
  return [
    "{",
    `  "_generatedBy": ${JSON.stringify(header.trim().split("\n").map(line => line.replace(/^\/\/\s?/, "")).join(" | "))},`,
    `  "name": ${JSON.stringify(packageName)},`,
    `  "version": "0.1.0",`,
    `  "type": "module",`,
    `  "private": true,`,
    `  "engines": { "node": ">=24" },`,
    `  "scripts": {`,
    `    "build": "tsc --noEmit false",`,
    `    "test": "npm run build && node --test dist/test/*.test.js",`,
    `    "start": "npm run build && node dist/src/main.js"`,
    `  },`,
    `  "devDependencies": {`,
    `    "@types/node": "^24",`,
    `    "typescript": "^5"`,
    `  }`,
    "}",
    "",
  ].join("\n");
}

function tsconfigJson(header: string): string {
  return [
    "{",
    `  "_generatedBy": ${JSON.stringify(header.trim().split("\n").map(line => line.replace(/^\/\/\s?/, "")).join(" | "))},`,
    `  "compilerOptions": {`,
    `    "target": "ES2024",`,
    `    "module": "NodeNext",`,
    `    "moduleResolution": "NodeNext",`,
    `    "strict": true,`,
    `    "noUncheckedIndexedAccess": true,`,
    `    "exactOptionalPropertyTypes": true,`,
    `    "rootDir": ".",`,
    `    "outDir": "dist",`,
    `    "declaration": true,`,
    `    "esModuleInterop": true,`,
    `    "skipLibCheck": true,`,
    `    "forceConsistentCasingInFileNames": true`,
    `  },`,
    `  "include": ["src/**/*.ts", "test/**/*.ts"]`,
    "}",
    "",
  ].join("\n");
}

function mainFile(header: string): string {
  return [
    header,
    `import { createServer } from "node:http";`,
    `import { Handler } from "./http/handler.js";`,
    "",
    "const handler = new Handler();",
    "const server = createServer((request, response) => handler.serve(request, response));",
    "const port = Number(process.env.PORT ?? \"8080\");",
    "server.listen(port);",
    "",
  ].join("\n");
}

function domainFile(header: string, className: string): string {
  return [
    header,
    `export class ${className} {}`,
    "",
  ].join("\n");
}

function useCaseFile(header: string, className: string): string {
  return [
    header,
    `export interface ${className} {`,
    "  execute(): Promise<void>;",
    "}",
    "",
  ].join("\n");
}

function portFile(header: string, className: string): string {
  return [
    header,
    `export interface ${className} {}`,
    "",
  ].join("\n");
}

function adapterFile(header: string, className: string): string {
  return [
    header,
    `export class ${className} {}`,
    "",
  ].join("\n");
}

function repositoryFile(header: string, className: string): string {
  return [
    header,
    `export interface ${className} {}`,
    "",
  ].join("\n");
}

function handlerFile(header: string): string {
  return [
    header,
    `import type { IncomingMessage, ServerResponse } from "node:http";`,
    "",
    "export class Handler {",
    "  serve(request: IncomingMessage, response: ServerResponse): void {",
    "    void request;",
    "    response.statusCode = 200;",
    "    response.setHeader(\"content-type\", \"application/json\");",
    "    response.end(JSON.stringify({ status: \"runspec-generated\" }));",
    "  }",
    "}",
    "",
  ].join("\n");
}

function scenarioTestFile(header: string, scenarioTitle: string): string {
  const escapedTitle = JSON.stringify(scenarioTitle);
  return [
    header,
    `import test from "node:test";`,
    "",
    `test(${escapedTitle}, { skip: "runspec scenario not yet implemented" }, () => {});`,
    "",
  ].join("\n");
}

function npmPackageName(input: string): string {
  const normalised = input
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, "-")
    .replace(/^[._-]+|[._-]+$/g, "")
    .replace(/-+/g, "-");
  return normalised.length > 0 ? normalised : "service";
}
