import type {
  GeneratedFile,
  ProductCapability,
  ServiceTarget,
  SkeletonGenerator,
} from "../model.js";
import { skeletonGenerator } from "../builders.js";

export const springBootGenerator: SkeletonGenerator = skeletonGenerator({
  id: "spring-boot",
  description: "Java Spring Boot service skeleton generator",
  language: "java",
  framework: "spring-boot",
  generate(capability, service) {
    const packageSegment = javaPackageSegment(service.id);
    const packageName = `com.example.${packageSegment}`;
    const packagePath = packageName.replace(/\./g, "/");
    const mainClassName = `${pascalCase(service.id)}Application`;
    const header = generatedHeader(capability, service);
    const files: GeneratedFile[] = [];

    files.push({ path: "pom.xml", content: pomXml(service.id) });
    files.push({
      path: `src/main/java/${packagePath}/${mainClassName}.java`,
      content: applicationFile(header, packageName, mainClassName),
    });

    capability.implementation.domainObjects.forEach(name => {
      const className = pascalCase(name);
      files.push({
        path: `src/main/java/${packagePath}/domain/${className}.java`,
        content: domainFile(header, packageName, className),
      });
    });
    capability.implementation.useCases.forEach(name => {
      const className = pascalCase(name);
      files.push({
        path: `src/main/java/${packagePath}/application/${className}.java`,
        content: useCaseFile(header, packageName, className),
      });
    });
    capability.implementation.ports.forEach(name => {
      const className = pascalCase(name);
      files.push({
        path: `src/main/java/${packagePath}/ports/${className}.java`,
        content: portFile(header, packageName, className),
      });
    });
    capability.implementation.adapters.forEach(name => {
      const className = pascalCase(name);
      files.push({
        path: `src/main/java/${packagePath}/adapters/${className}.java`,
        content: adapterFile(header, packageName, className),
      });
    });
    capability.implementation.repositories.forEach(name => {
      const className = pascalCase(name);
      files.push({
        path: `src/main/java/${packagePath}/repositories/${className}.java`,
        content: repositoryFile(header, packageName, className),
      });
    });

    files.push({
      path: `src/main/java/${packagePath}/controllers/HelloController.java`,
      content: controllerFile(header, packageName),
    });

    capability.scenarios.forEach(scenario => {
      const className = `${pascalCase(scenario.id)}Test`;
      files.push({
        path: `src/test/java/${packagePath}/${className}.java`,
        content: scenarioTestFile(header, packageName, className, scenario.title),
      });
    });

    return files;
  },
});

function generatedHeader(capability: ProductCapability, service: ServiceTarget): string {
  return [
    "// Code generated by runspec. DO NOT EDIT.",
    `// Source: capability "${capability.id}", service "${service.id}".`,
    "",
  ].join("\n");
}

function pomXml(artifactId: string): string {
  return [
    `<?xml version="1.0" encoding="UTF-8"?>`,
    `<project xmlns="http://maven.apache.org/POM/4.0.0"`,
    `         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"`,
    `         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">`,
    `  <modelVersion>4.0.0</modelVersion>`,
    `  <parent>`,
    `    <groupId>org.springframework.boot</groupId>`,
    `    <artifactId>spring-boot-starter-parent</artifactId>`,
    `    <version>3.5.0</version>`,
    `    <relativePath/>`,
    `  </parent>`,
    `  <groupId>com.example</groupId>`,
    `  <artifactId>${escapeXml(artifactId)}</artifactId>`,
    `  <version>0.1.0</version>`,
    `  <properties>`,
    `    <java.version>21</java.version>`,
    `  </properties>`,
    `  <dependencies>`,
    `    <dependency>`,
    `      <groupId>org.springframework.boot</groupId>`,
    `      <artifactId>spring-boot-starter-web</artifactId>`,
    `    </dependency>`,
    `    <dependency>`,
    `      <groupId>org.springframework.boot</groupId>`,
    `      <artifactId>spring-boot-starter-test</artifactId>`,
    `      <scope>test</scope>`,
    `    </dependency>`,
    `  </dependencies>`,
    `  <build>`,
    `    <plugins>`,
    `      <plugin>`,
    `        <groupId>org.springframework.boot</groupId>`,
    `        <artifactId>spring-boot-maven-plugin</artifactId>`,
    `      </plugin>`,
    `    </plugins>`,
    `  </build>`,
    `</project>`,
    "",
  ].join("\n");
}

function applicationFile(header: string, packageName: string, className: string): string {
  return [
    header,
    `package ${packageName};`,
    "",
    "import org.springframework.boot.SpringApplication;",
    "import org.springframework.boot.autoconfigure.SpringBootApplication;",
    "",
    "@SpringBootApplication",
    `public class ${className} {`,
    "    public static void main(String[] args) {",
    `        SpringApplication.run(${className}.class, args);`,
    "    }",
    "}",
    "",
  ].join("\n");
}

function domainFile(header: string, packageName: string, className: string): string {
  return [
    header,
    `package ${packageName}.domain;`,
    "",
    `public class ${className} {`,
    "}",
    "",
  ].join("\n");
}

function useCaseFile(header: string, packageName: string, className: string): string {
  return [
    header,
    `package ${packageName}.application;`,
    "",
    `public interface ${className} {`,
    "    void execute();",
    "}",
    "",
  ].join("\n");
}

function portFile(header: string, packageName: string, className: string): string {
  return [
    header,
    `package ${packageName}.ports;`,
    "",
    `public interface ${className} {`,
    "}",
    "",
  ].join("\n");
}

function adapterFile(header: string, packageName: string, className: string): string {
  return [
    header,
    `package ${packageName}.adapters;`,
    "",
    `public class ${className} {`,
    "}",
    "",
  ].join("\n");
}

function repositoryFile(header: string, packageName: string, className: string): string {
  return [
    header,
    `package ${packageName}.repositories;`,
    "",
    `public interface ${className} {`,
    "}",
    "",
  ].join("\n");
}

function controllerFile(header: string, packageName: string): string {
  return [
    header,
    `package ${packageName}.controllers;`,
    "",
    "import org.springframework.web.bind.annotation.GetMapping;",
    "import org.springframework.web.bind.annotation.RestController;",
    "",
    "@RestController",
    "public class HelloController {",
    "    @GetMapping(\"/\")",
    "    public String hello() {",
    "        return \"runspec generated\";",
    "    }",
    "}",
    "",
  ].join("\n");
}

function scenarioTestFile(header: string, packageName: string, className: string, scenarioTitle: string): string {
  const escapedTitle = scenarioTitle.replace(/\\/g, "\\\\").replace(/"/g, "\\\"");
  return [
    header,
    `package ${packageName};`,
    "",
    "import org.junit.jupiter.api.Disabled;",
    "import org.junit.jupiter.api.Test;",
    "",
    `@Disabled("runspec scenario not yet implemented: ${escapedTitle}")`,
    `public class ${className} {`,
    "    @Test",
    "    public void scenario() {",
    "    }",
    "}",
    "",
  ].join("\n");
}

function javaPackageSegment(input: string): string {
  const cleaned = input
    .toLowerCase()
    .replace(/[^a-z0-9]/g, "");
  if (cleaned.length === 0) {
    return "service";
  }
  return /^[0-9]/.test(cleaned) ? `s${cleaned}` : cleaned;
}

function pascalCase(input: string): string {
  const parts = input
    .replace(/[-_]+/g, " ")
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1 $2")
    .replace(/[^A-Za-z0-9 ]/g, " ")
    .split(/\s+/)
    .filter(part => part.length > 0);
  if (parts.length === 0) {
    return "Unnamed";
  }
  return parts.map(part => part.charAt(0).toUpperCase() + part.slice(1).toLowerCase()).join("");
}

function escapeXml(input: string): string {
  return input
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}
