import test from "node:test";
import assert from "node:assert/strict";
import { runSpecFramework } from "../../src/blueprint/runSpecFramework.js";
import { goHttpGenerator } from "../../src/core/generators/go-http.js";

const capability = runSpecFramework.productCapabilities.find(entry => entry.id === "APPLICATION_BUILDER");
const service = runSpecFramework.serviceTargets.find(entry => entry.id === "go-http-service");
if (capability === undefined || service === undefined) {
  throw new Error("test fixture missing APPLICATION_BUILDER or go-http-service");
}

test("goHttpGenerator emits a deterministic file set for the bootstrap blueprint", () => {
  const filesA = goHttpGenerator.generate(capability, service);
  const filesB = goHttpGenerator.generate(capability, service);
  assert.deepEqual(filesA, filesB);
});

test("goHttpGenerator produces go.mod with the expected module path", () => {
  const files = goHttpGenerator.generate(capability, service);
  const goMod = files.find(file => file.path === "go.mod");
  assert.ok(goMod);
  assert.match(goMod.content, /module example\.com\/go-http-service/);
  assert.match(goMod.content, /go 1\.22/);
});

test("goHttpGenerator emits one domain file per declared domain object", () => {
  const files = goHttpGenerator.generate(capability, service);
  const domainFiles = files.filter(file => file.path.startsWith("domain/"));
  assert.equal(domainFiles.length, capability.implementation.domainObjects.length);
  assert.ok(domainFiles.some(file => file.path === "domain/product_capability.go"));
  assert.ok(domainFiles.some(file => file.path === "domain/implementation_contract.go"));
});

test("goHttpGenerator emits a usecase file with the Execute interface", () => {
  const files = goHttpGenerator.generate(capability, service);
  const useCase = files.find(file => file.path === "usecases/generate_service_slice.go");
  assert.ok(useCase);
  assert.match(useCase.content, /package usecases/);
  assert.match(useCase.content, /type GenerateServiceSlice interface \{/);
  assert.match(useCase.content, /Execute\(\) error/);
});

test("goHttpGenerator emits an http handler with ServeHTTP signature", () => {
  const files = goHttpGenerator.generate(capability, service);
  const handler = files.find(file => file.path === "http/handler.go");
  assert.ok(handler);
  assert.match(handler.content, /func \(h \*Handler\) ServeHTTP\(w http\.ResponseWriter, r \*http\.Request\)/);
});

test("goHttpGenerator emits a test stub per scenario", () => {
  const files = goHttpGenerator.generate(capability, service);
  const testFiles = files.filter(file => file.path.startsWith("tests/"));
  assert.equal(testFiles.length, capability.scenarios.length);
  for (const testFile of testFiles) {
    assert.match(testFile.content, /package tests/);
    assert.match(testFile.content, /t\.Skip/);
  }
});

test("goHttpGenerator includes a generated-by header citing capability and service", () => {
  const files = goHttpGenerator.generate(capability, service);
  for (const file of files) {
    if (file.path === "go.mod") {
      continue;
    }
    assert.match(file.content, /Code generated by runspec\. DO NOT EDIT\./);
    assert.match(file.content, new RegExp(`capability "${capability.id}", service "${service.id}"`));
  }
});
