import test from "node:test";
import assert from "node:assert/strict";
import { runSpecFramework } from "../../src/blueprint/runSpecFramework.js";
import { nodeHttpGenerator } from "../../src/core/generators/node-http.js";

const capability = runSpecFramework.productCapabilities.find(entry => entry.id === "APPLICATION_BUILDER");
const service = runSpecFramework.serviceTargets.find(entry => entry.id === "typescript-node-service");
if (capability === undefined || service === undefined) {
  throw new Error("test fixture missing APPLICATION_BUILDER or typescript-node-service");
}

test("nodeHttpGenerator emits a deterministic file set", () => {
  const a = nodeHttpGenerator.generate(capability, service);
  const b = nodeHttpGenerator.generate(capability, service);
  assert.deepEqual(a, b);
});

test("nodeHttpGenerator package.json declares the service name and Node >=24", () => {
  const files = nodeHttpGenerator.generate(capability, service);
  const pkg = files.find(file => file.path === "package.json");
  assert.ok(pkg);
  const parsed = JSON.parse(pkg.content) as { name?: string; engines?: { node?: string } };
  assert.equal(parsed.name, "typescript-node-service");
  assert.equal(parsed.engines?.node, ">=24");
});

test("nodeHttpGenerator tsconfig.json enables strict + noUncheckedIndexedAccess", () => {
  const files = nodeHttpGenerator.generate(capability, service);
  const tsconfig = files.find(file => file.path === "tsconfig.json");
  assert.ok(tsconfig);
  const parsed = JSON.parse(tsconfig.content) as { compilerOptions?: Record<string, unknown> };
  assert.equal(parsed.compilerOptions?.["strict"], true);
  assert.equal(parsed.compilerOptions?.["noUncheckedIndexedAccess"], true);
});

test("nodeHttpGenerator main.ts wires createServer to the Handler class", () => {
  const files = nodeHttpGenerator.generate(capability, service);
  const main = files.find(file => file.path === "src/main.ts");
  assert.ok(main);
  assert.match(main.content, /import \{ createServer \} from "node:http"/);
  assert.match(main.content, /new Handler\(\)/);
  assert.match(main.content, /server\.listen\(port\)/);
});

test("nodeHttpGenerator emits one TS file per domain object preserving PascalCase", () => {
  const files = nodeHttpGenerator.generate(capability, service);
  const domainFiles = files.filter(file => file.path.startsWith("src/domain/"));
  assert.equal(domainFiles.length, capability.implementation.domainObjects.length);
  const productCapability = domainFiles.find(file => file.path === "src/domain/ProductCapability.ts");
  assert.ok(productCapability);
  assert.match(productCapability.content, /export class ProductCapability \{\}/);
});

test("nodeHttpGenerator use case interface declares execute returning Promise<void>", () => {
  const files = nodeHttpGenerator.generate(capability, service);
  const useCase = files.find(file => file.path === "src/usecases/GenerateServiceSlice.ts");
  assert.ok(useCase);
  assert.match(useCase.content, /export interface GenerateServiceSlice \{/);
  assert.match(useCase.content, /execute\(\): Promise<void>;/);
});

test("nodeHttpGenerator handler responds with JSON over node:http types", () => {
  const files = nodeHttpGenerator.generate(capability, service);
  const handler = files.find(file => file.path === "src/http/handler.ts");
  assert.ok(handler);
  assert.match(handler.content, /import type \{ IncomingMessage, ServerResponse \} from "node:http"/);
  assert.match(handler.content, /response\.setHeader\("content-type", "application\/json"\)/);
});

test("nodeHttpGenerator emits a node:test stub per scenario", () => {
  const files = nodeHttpGenerator.generate(capability, service);
  const testFiles = files.filter(file => file.path.startsWith("test/"));
  assert.equal(testFiles.length, capability.scenarios.length);
  for (const testFile of testFiles) {
    assert.match(testFile.content, /import test from "node:test";/);
    assert.match(testFile.content, /skip: "runspec scenario not yet implemented"/);
  }
});

test("nodeHttpGenerator carries the generated-by header in every file", () => {
  const files = nodeHttpGenerator.generate(capability, service);
  for (const file of files) {
    assert.ok(
      file.content.includes("Code generated by runspec. DO NOT EDIT."),
      `missing generated-by marker in ${file.path}`,
    );
    const sourceFragment = file.path.endsWith(".json")
      ? `Source: capability \\\"${capability.id}\\\", service \\\"${service.id}\\\"`
      : `Source: capability "${capability.id}", service "${service.id}"`;
    assert.ok(
      file.content.includes(sourceFragment),
      `missing source citation in ${file.path}`,
    );
  }
});

test("nodeHttpGenerator sanitises control characters in capability and service ids", () => {
  const capabilityWithControlId = { ...capability, id: "BAD\nID\tWITH\rCONTROL" };
  const serviceWithControlId = { ...service, id: "svc\nname" };
  const files = nodeHttpGenerator.generate(capabilityWithControlId, serviceWithControlId);
  for (const file of files) {
    if (file.path === "package.json" || file.path === "tsconfig.json") {
      continue;
    }
    const sourceLine = file.content.split("\n").find(line => line.startsWith("// Source:"));
    assert.ok(sourceLine, `missing Source header in ${file.path}`);
    assert.ok(!/[\r\t]/.test(sourceLine), `control char leaked into header of ${file.path}: ${JSON.stringify(sourceLine)}`);
  }
});

test("nodeHttpGenerator escapes scenario titles inside the test() name argument", () => {
  const scenarioWithSpecials = {
    ...capability,
    scenarios: [
      {
        ...capability.scenarios[0]!,
        id: "SPECIAL_TITLE",
        title: 'scenario with "quote" and \\backslash and \nnewline',
      },
    ],
  };
  const files = nodeHttpGenerator.generate(scenarioWithSpecials, service);
  const testFile = files.find(file => file.path.startsWith("test/"));
  assert.ok(testFile);
  const testCallLines = testFile.content.split("\n").filter(line => line.startsWith("test("));
  assert.equal(testCallLines.length, 1, "title with raw newline leaked across lines");
  const callLine = testCallLines[0]!;
  assert.ok(callLine.includes("\\n"), "newline in title was not escaped");
  assert.ok(callLine.includes("\\\""), "double-quote in title was not escaped");
  assert.ok(callLine.includes("\\\\"), "backslash in title was not escaped");
});

test("nodeHttpGenerator normalises hostile service ids in package.json name", () => {
  const hostileService = { ...service, id: "../etc passwd!" };
  const files = nodeHttpGenerator.generate(capability, hostileService);
  const pkg = files.find(file => file.path === "package.json");
  assert.ok(pkg);
  const parsed = JSON.parse(pkg.content) as { name?: string };
  assert.ok(parsed.name);
  assert.match(parsed.name, /^[a-z0-9._-]+$/);
  assert.ok(!parsed.name.startsWith("."));
  assert.ok(!parsed.name.startsWith("-"));
  assert.ok(!parsed.name.endsWith("-"));
});
